@extends('user.layouts.app')
@section('title', 'À propos')
@section('content')
<div class="page-banner-area overlay section"><div class="container"><div class="row"><div class="page-banner text-center col-xs-12"><h1>À propos de l’ABE</h1><ul class="breadcrumb"><li><a href="{{ route('home') }}">Accueil</a></li><li>À propos</li></ul></div></div></div></div>
<section class="about-area section bg-white pt-120 pb-100"><div class="container"><div class="row align-items-center">
    <div class="col-lg-6 col-12 mb-30"><div class="abe-image-frame"><img src="/storage/demo/abe/galerie-communaute.jpg" alt="Action communautaire de l’Académie du Bien-Être"></div></div>
    <div class="col-lg-6 col-12 mb-30"><span class="abe-kicker">QUI SOMMES-NOUS ?</span><h2>Une association tournée vers l’accompagnement et l’autonomie</h2><p>L’Académie du Bien-Être œuvre auprès des personnes et des communautés à travers des programmes éducatifs, entrepreneuriaux et de promotion de la santé.</p><p>Notre approche crée des espaces d’écoute, d’apprentissage et de participation permettant à chacun de renforcer ses capacités et de devenir acteur de son parcours.</p><a class="abe-text-link" href="{{ route('contact') }}">Échanger avec notre équipe <i class="fa fa-arrow-right"></i></a></div>
</div></div></section>
<section class="abe-section abe-pillars-section section"><div class="container"><div class="abe-section-heading"><span class="abe-kicker">NOTRE MANIÈRE D’AGIR</span><h2>Proches des besoins, orientés vers les solutions</h2></div><div class="row g-4"><div class="col-md-4"><article class="abe-pillar"><span><i class="fa fa-handshake-o"></i></span><h3>Accompagner</h3><p>Écouter, orienter et proposer un cadre adapté aux besoins des bénéficiaires.</p></article></div><div class="col-md-4"><article class="abe-pillar"><span><i class="fa fa-graduation-cap"></i></span><h3>Former</h3><p>Développer les connaissances et compétences utiles à une autonomie durable.</p></article></div><div class="col-md-4"><article class="abe-pillar"><span><i class="fa fa-users"></i></span><h3>Mobiliser</h3><p>Créer des collaborations autour d’actions d’intérêt collectif et de proximité.</p></article></div></div></div></section>
@endsection
