@extends('user.layouts.app')
@section('title', 'Accueil')
@section('content')
<section class="abe-hero section"><div class="container"><div class="abe-hero-content"><span class="abe-kicker">ACADÉMIE DU BIEN-ÊTRE · YAOUNDÉ</span><h1>Donner à chacun les moyens de construire son avenir.</h1><p>L’ABE accompagne les enfants, les jeunes et les familles par l’éducation, l’entrepreneuriat et la promotion de la santé.</p><div class="abe-hero-actions"><a class="abe-btn abe-btn-primary" href="{{ route('programme') }}">Découvrir nos programmes</a><a class="abe-btn abe-btn-secondary" href="{{ route('contact') }}">Devenir partenaire</a></div></div></div></section>

<section class="abe-trust-strip section"><div class="container"><div><strong>3 axes d’action</strong><span>Une approche globale du bien-être</span></div><div><strong>Ancrage local</strong><span>Des actions proches des communautés</span></div><div><strong>Impact durable</strong><span>Autonomie, prévention et transmission</span></div></div></section>

<section class="abe-section abe-intro section"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-6"><div class="abe-image-frame"><img src="/storage/demo/abe/galerie-solidarite.jpg" alt="Accompagnement communautaire"></div></div><div class="col-lg-6"><span class="abe-kicker">NOTRE ENGAGEMENT</span><h2>Le bien-être commence par la possibilité d’apprendre, d’agir et de prendre soin de soi.</h2><p>L’Académie du Bien-Être crée des espaces d’écoute, de formation et de mobilisation au service des personnes et des communautés.</p><a class="abe-text-link" href="{{ route('about') }}">Découvrir notre approche <i class="fa fa-arrow-right"></i></a></div></div></div></section>

<section class="abe-section abe-pillars-section section"><div class="container"><div class="abe-section-heading"><span class="abe-kicker">NOS PRIORITÉS</span><h2>Trois piliers pour agir durablement</h2><p>Des réponses concrètes et complémentaires aux besoins des communautés.</p></div><div class="row g-4"><div class="col-lg-4"><article class="abe-pillar"><span><i class="fa fa-book"></i></span><h3>Soutien éducatif</h3><p>Renforcer les apprentissages, l’orientation et la confiance des enfants et des jeunes.</p></article></div><div class="col-lg-4"><article class="abe-pillar"><span><i class="fa fa-line-chart"></i></span><h3>Entrepreneuriat</h3><p>Accompagner les femmes et les jeunes vers des activités économiques viables et autonomes.</p></article></div><div class="col-lg-4"><article class="abe-pillar"><span><i class="fa fa-heartbeat"></i></span><h3>Santé pour tous</h3><p>Informer, prévenir et rapprocher les services essentiels des familles et des communautés.</p></article></div></div></div></section>

<section class="abe-section section"><div class="container"><div class="abe-section-heading is-split"><div><span class="abe-kicker">NOS PROGRAMMES</span><h2>Transformer les intentions en actions</h2></div><a class="abe-text-link" href="{{ route('programme') }}">Voir tous les programmes <i class="fa fa-arrow-right"></i></a></div><div class="row g-4">@forelse($programmes as $programme)<div class="col-lg-4 col-md-6"><article class="abe-content-card"><a class="abe-card-image" href="{{ route('programme.details', $programme) }}"><img src="{{ $programme->image_url }}" alt="{{ $programme->nom }}" loading="lazy"><span>Programme</span></a><div class="abe-card-body"><h3><a href="{{ route('programme.details', $programme) }}">{{ $programme->nom }}</a></h3><p>{{ Str::limit($programme->description, 145) }}</p><a class="abe-text-link" href="{{ route('programme.details', $programme) }}">En savoir plus <i class="fa fa-arrow-right"></i></a></div></article></div>@empty<div class="col-12"><p>Aucun programme publié pour le moment.</p></div>@endforelse</div></div></section>

<section class="abe-section abe-events-section section"><div class="container"><div class="abe-section-heading is-split"><div><span class="abe-kicker">AGENDA</span><h2>Nos prochains rendez-vous</h2></div><a class="abe-text-link" href="{{ route('event') }}">Tout l’agenda <i class="fa fa-arrow-right"></i></a></div><div class="row g-4">@forelse($evenements as $evenement)<div class="col-lg-4"><article class="abe-event-card"><a href="{{ route('event.details', $evenement) }}"><img src="{{ $evenement->image_url }}" alt="{{ $evenement->titre }}" loading="lazy"></a><div class="abe-event-date"><strong>{{ $evenement->date->format('d') }}</strong><span>{{ mb_strtoupper($evenement->date->translatedFormat('M')) }}</span></div><div><p class="abe-meta"><i class="fa fa-map-marker"></i> {{ $evenement->lieu }}</p><h3><a href="{{ route('event.details', $evenement) }}">{{ $evenement->titre }}</a></h3><p>{{ Str::limit($evenement->description, 105) }}</p></div></article></div>@empty<div class="col-12"><p>Aucun événement programmé.</p></div>@endforelse</div></div></section>

@if($images->isNotEmpty())<section class="abe-section abe-gallery-preview section"><div class="container"><div class="abe-section-heading is-split"><div><span class="abe-kicker">SUR LE TERRAIN</span><h2>Nos actions en images</h2></div><a class="abe-text-link" href="{{ route('gallery') }}">Explorer la galerie <i class="fa fa-arrow-right"></i></a></div><div class="abe-gallery-grid">@foreach($images->take(6) as $image)<a href="{{ $image->image_url }}" class="image-popup"><img src="{{ $image->image_url }}" alt="Action de l’Académie du Bien-Être" loading="lazy"></a>@endforeach</div></div></section>@endif

<section class="abe-section section"><div class="container"><div class="abe-section-heading is-split"><div><span class="abe-kicker">ACTUALITÉS</span><h2>Les dernières nouvelles de l’ABE</h2></div><a class="abe-text-link" href="{{ route('news') }}">Toutes les actualités <i class="fa fa-arrow-right"></i></a></div><div class="row g-4">@forelse($actualites as $actualite)<div class="col-lg-4 col-md-6"><article class="abe-content-card"><a class="abe-card-image" href="{{ route('news.details', $actualite) }}"><img src="{{ $actualite->image_url }}" alt="{{ $actualite->titre }}" loading="lazy"></a><div class="abe-card-body"><p class="abe-meta"><i class="fa fa-calendar"></i> {{ $actualite->date_publication->translatedFormat('d F Y') }}</p><h3><a href="{{ route('news.details', $actualite) }}">{{ $actualite->titre }}</a></h3><p>{{ Str::limit($actualite->contenu, 125) }}</p></div></article></div>@empty<div class="col-12"><p>Aucune actualité publiée.</p></div>@endforelse</div></div></section>

<section class="abe-cta section"><div class="container"><div><span class="abe-kicker">AGISSONS ENSEMBLE</span><h2>Vous souhaitez soutenir une action ou proposer un partenariat ?</h2><p>Échangeons sur les besoins de votre communauté et les possibilités de collaboration.</p></div><a class="abe-btn abe-btn-light" href="{{ route('contact') }}">Parler à notre équipe</a></div></section>
@endsection
